In [2]:
import torch
import numpy as np

In [3]:
print(torch.__version__)

1.1.0


In [4]:
tensor_array=torch.Tensor([[1,2],[3,4]])

In [5]:
print(tensor_array)

tensor([[1., 2.],
        [3., 4.]])


In [7]:
tensor_uninitialized = torch.Tensor(3,3)
tensor_uninitialized

tensor([[ 8.5843e-19,  4.5835e-41, -4.6607e-06],
        [ 3.0623e-41,  0.0000e+00,  0.0000e+00],
        [ 1.8077e-43,  0.0000e+00, -4.8363e-06]])

In [8]:
torch.numel(tensor_uninitialized)

9

In [9]:
tenor_initlized = torch.rand(3,3)
tenor_initlized

tensor([[0.7255, 0.6340, 0.9938],
        [0.5112, 0.6317, 0.3411],
        [0.2922, 0.3457, 0.1487]])

In [14]:
tensor_int = torch.randn(2,3).type(torch.IntTensor)
tensor_int

tensor([[ 0, -1, -1],
        [ 0,  0,  0]], dtype=torch.int32)

In [17]:
tensor_long = torch.LongTensor([1,2,3])
print(tensor_long)
print(tensor_long.type())

tensor([1, 2, 3])
torch.LongTensor


In [20]:
tensor_byte = torch.ByteTensor([1,258,128,-9])
tensor_byte

tensor([  1,   2, 128, 247], dtype=torch.uint8)

In [21]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
tensor_zeros = torch.zeros(1,10)
tensor_zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
tensor_eye = torch.eye(2,3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [34]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1]])

In [35]:
tensor_one_shape_eyes = torch.ones_like(tensor_eye)
tensor_one_shape_eyes

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [37]:
tenor_initlized.fill_(2)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [39]:
new_tensor = tenor_initlized.add(3)
new_tensor

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [49]:
import numpy as np
array=np.array([1,2,3])
array

array([1, 2, 3])

In [50]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3])

In [51]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [53]:
array[1]=200
array

array([  1, 200,   3])

In [54]:
tensor

tensor([  1, 200,   3])

In [56]:
initial_tensor = torch.rand(2,3,3)
initial_tensor

tensor([[[0.7193, 0.2958, 0.0688],
         [0.4589, 0.9748, 0.0726],
         [0.3349, 0.4166, 0.8207]],

        [[0.6809, 0.2977, 0.3887],
         [0.9160, 0.7629, 0.2372],
         [0.0473, 0.4165, 0.5959]]])

In [57]:
initial_tensor[0]

tensor([[0.7193, 0.2958, 0.0688],
        [0.4589, 0.9748, 0.0726],
        [0.3349, 0.4166, 0.8207]])

In [68]:
initial_tensor[0][:]

tensor([[0.7193, 0.2958, 0.0688],
        [0.4589, 0.9748, 0.0726],
        [0.3349, 0.4166, 0.8207]])

In [69]:
initial_tensor[0][:][1:]

tensor([[0.4589, 0.9748, 0.0726],
        [0.3349, 0.4166, 0.8207]])

In [66]:
initial_tensor[0][:][1:][0][1:][0]

tensor(0.9748)

In [70]:
initial_tensor.size()

torch.Size([2, 3, 3])

In [71]:
initial_tensor.shape

torch.Size([2, 3, 3])

In [74]:
reshpaed=initial_tensor.view(18)
reshpaed

tensor([0.7193, 0.2958, 0.0688, 0.4589, 0.9748, 0.0726, 0.3349, 0.4166, 0.8207,
        0.6809, 0.2977, 0.3887, 0.9160, 0.7629, 0.2372, 0.0473, 0.4165, 0.5959])

In [77]:
initial_tensor[0][0][0]=100
initial_tensor

tensor([[[1.0000e+02, 2.9578e-01, 6.8804e-02],
         [4.5893e-01, 9.7481e-01, 7.2581e-02],
         [3.3486e-01, 4.1660e-01, 8.2065e-01]],

        [[6.8089e-01, 2.9771e-01, 3.8867e-01],
         [9.1598e-01, 7.6290e-01, 2.3721e-01],
         [4.7269e-02, 4.1646e-01, 5.9591e-01]]])

In [78]:
reshpaed

tensor([1.0000e+02, 2.9578e-01, 6.8804e-02, 4.5893e-01, 9.7481e-01, 7.2581e-02,
        3.3486e-01, 4.1660e-01, 8.2065e-01, 6.8089e-01, 2.9771e-01, 3.8867e-01,
        9.1598e-01, 7.6290e-01, 2.3721e-01, 4.7269e-02, 4.1646e-01, 5.9591e-01])

In [81]:
reshaped = initial_tensor.view(2,9)
reshaped

tensor([[1.0000e+02, 2.9578e-01, 6.8804e-02, 4.5893e-01, 9.7481e-01, 7.2581e-02,
         3.3486e-01, 4.1660e-01, 8.2065e-01],
        [6.8089e-01, 2.9771e-01, 3.8867e-01, 9.1598e-01, 7.6290e-01, 2.3721e-01,
         4.7269e-02, 4.1646e-01, 5.9591e-01]])

In [84]:
reshaped[0][0]=1

In [85]:
initial_tensor

tensor([[[1.0000, 0.2958, 0.0688],
         [0.4589, 0.9748, 0.0726],
         [0.3349, 0.4166, 0.8207]],

        [[0.6809, 0.2977, 0.3887],
         [0.9160, 0.7629, 0.2372],
         [0.0473, 0.4165, 0.5959]]])

In [89]:
initial_tensor.view(-1,3,2).shape

torch.Size([3, 3, 2])

In [90]:
initial_tensor.view(2,-1,1).shape

torch.Size([2, 9, 1])

In [93]:
initial_tensor=torch.rand(2,3)
initial_tensor

tensor([[0.9626, 0.9588, 0.9582],
        [0.4922, 0.0592, 0.4034]])

In [100]:
sorted_tensor,sorted_indices = torch.sort(initial_tensor,1)
sorted_tensor
sorted_indices

tensor([[2, 1, 0],
        [1, 2, 0]])

In [101]:
sorted_tensor,sorted_indices = torch.sort(initial_tensor,0)
sorted_tensor
sorted_indices

tensor([[1, 1, 1],
        [0, 0, 0]])

In [102]:
sorted_tensor,sorted_indices = torch.sort(initial_tensor,2)
sorted_tensor
sorted_indices

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)